### ISSUE TITLE
Why my file gen is 4GB

### ISSUE THREAD

**Issue by hungcuiga1** [arkku/srec#3] opened 2023-10-09 15:22 UTC
Maybe this code is not work in 2023 or .... This result binary file(.bin) is 4GB for any data

**Comment by arkku** [comment] 2023-10-09 16:09
@hungcuiga1 Hi, if you are talking about the `srec2bin` example program, please try specifying the `-A` (uppercase!) argument. I suspect that your SREC input file specifies the first address at 4GB, and the program is simply doing as it is told and seeking to that address.

If this doesn't solve it, please give the input file and steps to reproduce the issue.

(Note that the `srec2bin` is just an example program, the main point of this repository is to provide a library for reading SREC files programmatically, especially in embedded systems, in which case you might want to write to a specific address space and don't want the SREC file to start from zero offset.)

**Comment by hungcuiga1** [comment] 2023-10-10 02:14
@arkku Hi, I can't solve it. 
![image](https://github.com/arkku/srec/assets/44896903/8f5c24d2-02ae-4906-a509-b6c330383a73)
4GB is size of .bin file gen. How about you!

**Comment by arkku** [comment] 2023-10-10 09:10
@hungcuiga1 Please give the input file and the steps to reproduce the issue (e.g., exact command-line you used)

(Running `make test` passes for me, so my hypothesis is that your input file just specifies addresses that extend to 4 GB, and thus this is the correct result for that file, but can't confirm without seeing the input.)

edit: If the input file is large, try to make a smaller one by deleting lines (and verify that the smaller file still has the same issue).

**Comment by hungcuiga1** [comment] 2023-10-10 13:48
@arkku 
I use "gcc srec2bin.c kk_srec.c" to build and get a file a.exe--> i use command "a -A -o aaaa.bin -i 2.srec"
This is my file "2.srec": 
S321000808FC843098FF8C3098FF0028FBFF1020C5FF1420C5FF1820C5FF0020C5FF46
S321000809182020C5FF2420C5FF2820C5FF1008C5FF1408C5FF1808C5FF0008C5FF31
S321000809341000C5FF1400C5FF1800C5FF0000C5FF1001C5FF1401C5FF1801C5FFC2
S321000809500001C5FF2008C5FF2408C5FF2808C5FF2000C5FF2400C5FF2800C5FF30
S3210008096C2001C5FF2401C5FF2801C5FF009198FF089198FF0C9198FFE1015203E3
S321000809880000000008000000700198FF780198FF500198FF580198FF400198FF75
S321000809A4480198FF208298FF288298FF108298FF188298FF008398FF088398FF39
S31D000809C0008298FF088298FF508298FF588298FF608298FF688298FF03
S321FDC0032C00000000010000000000000000000000000000000000000000000000F1
Thank you!

**Comment by arkku** [comment] 2023-10-10 14:30
So, the first address in that file is `0x000808FC` the rest of the lines continue from that, but the address on the last line is non-contiguous with the rest at `0xFDC0032C`, which is about 4,157,440 KiB as you have discovered.

i.e., the program is working correctly, but your input data has a 4060 megabyte gap. It is probably not meant to go in a single binary file.

**Comment by arkku** [comment] 2023-10-10 14:33
(Since the next-to-last line is shorter than the others, I suspect the actual data ends there and the last line is meant to be written to some specific address on a real device to set something like fuses. If you are only interested in the data before that, simply delete the last line from the input.)

**Comment by arkku** [comment] 2023-10-10 14:48
Closing as the input data contains addresses from a ~4 GB range, causing the inflated file size.

**Closed as completed by arkku** 2023-10-10 14:48 UTC

**Comment by hungcuiga1** [comment] 2023-10-10 15:59
Hi @arkku , Thank you! I understand it, but why I convert from .srec to .bin and use this .bin to convert to .srec, two file .srec is different as below:
1/ 
![image](https://github.com/arkku/srec/assets/44896903/ffcdfc75-9162-46b7-ada2-c622ab0312a4)
2/ 
![image](https://github.com/arkku/srec/assets/44896903/294100a5-dc23-4c81-9eb9-abdea6aa1d46)
I see in origin file have max 70 char in line but in file 2/ i see 78 char in a line , S321->S325
Thank you so much!

**Comment by arkku** [comment] 2023-10-10 19:41
@hungcuiga1 There is no canonical SREC representation, i.e., the same binary can be represented in infinitely many different ways in valid SREC format. Also, your original SREC file has gaps in the data – not just the ~4060 MB gap we discussed earlier, but also ~1 KB gap between the 0x01C address on line two and and the 0x400 address on line three.

This gap ~1 KB near the beginning of the file is why there are all those lines with `0000…` data in them. The reason why the lines are different length is just a choice (you can change this in the code, search for `PAYLOAD_PER_LINE`), and the alignment of data on the SREC lines depends on this choice (as well as the starting address, but in this case it makes no difference).

Please also understand that the "bin" format means literally any file at all: the `srec2bin` just dumbly outputs the binary payload in the SREC file to a binary file, and the `bin2srec` just dumbly reads every byte of input in sequence and converts it to an SREC file without any understanding of the input. Meanwhile each data line in the SREC format specifies an address for that line, so it can represent "jumps" to different addresses.

In the case of your data here, there's probably at least 3 separate "segments" of binary data in it, that simply cannot be represented in a single contiguous sequence of bytes.

Anyway, the main purpose of this repository is to provide a _programming library_ for reading the SREC format, so assuming you know what the SREC file's data is supposed to be used for, the solution would be to write a custom program to read it and convert it properly, e.g., you could output three different files to represent the parts separated by gaps, and/or parse the payload in those parts to output what you actually want to get out of the data.

**Comment by hungcuiga1** [comment] 2023-10-11 01:30
Thank you so much @arkku
